global:
    scrape_interval: 4s

scrape_configs:
    - job_name: 'leetcode-services'
      static_configs:
          - targets:
                - api-gateway:5000
                - users-service:5001
                - auth-service:5002
                - problems-service:5003
                - tags-service:5004
                - companies-service:5005
                - submissions-service:5006
                - execution-service:5007
