global:
    scrape_interval: 4s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets:
                [
                    'api-gateway:5000',
                    'users-service:9001',
                    'auth-service:9002',
                    'problems-service:9003',
                    'tags-service:9004',
                    'companies-service:9005',
                    'submissions-service:9006',
                    'execution-service:9007',
                ]
